apiVersion: v1
kind: Secret
metadata:
  name: coinlog-http-api-secret
  namespace: coinlog
  labels:
    app: coinlog-http-api
type: Opaque
stringData:
  db_conn_string: 'host=coinlog-postgres.coinlog.svc.cluster.local port=5432 user=postgres dbname=coinlog password=root sslmode=disable'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coinlog-http-api-config
  namespace: coinlog
  labels:
    app: coinlog-http-api
data:
  app_major_version: '1'
  server_port: ':8080'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coinlog-http-api
  namespace: coinlog
  labels:
    app: coinlog-http-api
spec:
  replicas: 3
  revisionHistoryLimit: 10
  minReadySeconds: 5
  selector:
    matchLabels:
      app: coinlog-http-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2
  template:
    metadata:
      labels:
        app: coinlog-http-api
        tier: application
    spec:
      containers:
        - name: coinlog
          image: coinlog/http-api:0.0.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: 64Mi
              cpu: 125m
            limits:
              memory: 128Mi
              cpu: 250m
          readinessProbe:
            # TODO: Add readiness-specific endpoint to app
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 5
          env:
            - name: NCORP_APPLICATION_MAJOR_VERSION
              valueFrom:
                configMapKeyRef:
                  name: coinlog-http-api-config
                  key: app_major_version
            - name: NCORP_SERVER_HTTP_LISTEN_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: coinlog-http-api-config
                  key: server_port
            - name: NCORP_DATABASE_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: coinlog-http-api-secret
                  key: db_conn_string
---
apiVersion: v1
kind: Service
metadata:
  name: coinlog-http-api-svc
  namespace: coinlog
  labels:
    app: coinlog-http-api
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: coinlog-http-api
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: coinlog-http-api
  namespace: coinlog
  annotations:
    kubernetes.io/ingress.class: nginx
    # USE in case of SPA web app
    # nginx.ingress.kubernetes.io/rewrite-target: /$1
  labels:
    app: coinlog-http-api
    tier: edge
spec:
  rules:
    - host: api.coinlog.info
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: coinlog-http-api-svc
                port:
                  number: 80