version: '3.9'
services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    restart: on-failure
    ports:
      - '6432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: coinlog
