package financialtransaction

import (
	"time"

	"github.com/maestre3d/coinlog/domain"
	"github.com/maestre3d/coinlog/domain/card"
	"github.com/maestre3d/coinlog/domain/contact"
	"github.com/maestre3d/coinlog/domain/financialaccount"
	"github.com/maestre3d/coinlog/domain/scheduledpayment"
	"github.com/maestre3d/coinlog/domain/user"
)

// FinancialTransaction record generated by the financial interaction between a User and a Contact.
//
// Assets could come from either FinancialAccount directly or from a Card; both instruments are mutually exclusive.
//
// Transactions could also be generated by ScheduledPayment(s).
type FinancialTransaction struct {
	ID                   string
	User                 user.User                         // req, FK -> users
	FinancialAccount     financialaccount.FinancialAccount // FK -> financial_accounts, nullable
	Card                 card.Card                         // FK -> cards, nullable
	Contact              contact.Contact                   // FK -> contacts
	FromScheduledPayment scheduledpayment.ScheduledPayment // FK -> scheduled_payments, nullable
	DisplayName          string                            // req
	Description          string
	Amount               float64
	Currency             string    // uses ISO-4127 standard
	OccurredAt           time.Time //req
	domain.Auditable
}
