// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/maestre3d/coinlog/ent/financialaccount"
	"github.com/maestre3d/coinlog/ent/predicate"
	"github.com/maestre3d/coinlog/ent/user"
)

// FinancialAccountQuery is the builder for querying FinancialAccount entities.
type FinancialAccountQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	inters     []Interceptor
	predicates []predicate.FinancialAccount
	withOwner  *UserQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the FinancialAccountQuery builder.
func (faq *FinancialAccountQuery) Where(ps ...predicate.FinancialAccount) *FinancialAccountQuery {
	faq.predicates = append(faq.predicates, ps...)
	return faq
}

// Limit the number of records to be returned by this query.
func (faq *FinancialAccountQuery) Limit(limit int) *FinancialAccountQuery {
	faq.limit = &limit
	return faq
}

// Offset to start from.
func (faq *FinancialAccountQuery) Offset(offset int) *FinancialAccountQuery {
	faq.offset = &offset
	return faq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (faq *FinancialAccountQuery) Unique(unique bool) *FinancialAccountQuery {
	faq.unique = &unique
	return faq
}

// Order specifies how the records should be ordered.
func (faq *FinancialAccountQuery) Order(o ...OrderFunc) *FinancialAccountQuery {
	faq.order = append(faq.order, o...)
	return faq
}

// QueryOwner chains the current query on the "owner" edge.
func (faq *FinancialAccountQuery) QueryOwner() *UserQuery {
	query := (&UserClient{config: faq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := faq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := faq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(financialaccount.Table, financialaccount.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, financialaccount.OwnerTable, financialaccount.OwnerColumn),
		)
		fromU = sqlgraph.SetNeighbors(faq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first FinancialAccount entity from the query.
// Returns a *NotFoundError when no FinancialAccount was found.
func (faq *FinancialAccountQuery) First(ctx context.Context) (*FinancialAccount, error) {
	nodes, err := faq.Limit(1).All(newQueryContext(ctx, TypeFinancialAccount, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{financialaccount.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (faq *FinancialAccountQuery) FirstX(ctx context.Context) *FinancialAccount {
	node, err := faq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first FinancialAccount ID from the query.
// Returns a *NotFoundError when no FinancialAccount ID was found.
func (faq *FinancialAccountQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = faq.Limit(1).IDs(newQueryContext(ctx, TypeFinancialAccount, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{financialaccount.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (faq *FinancialAccountQuery) FirstIDX(ctx context.Context) string {
	id, err := faq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single FinancialAccount entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one FinancialAccount entity is found.
// Returns a *NotFoundError when no FinancialAccount entities are found.
func (faq *FinancialAccountQuery) Only(ctx context.Context) (*FinancialAccount, error) {
	nodes, err := faq.Limit(2).All(newQueryContext(ctx, TypeFinancialAccount, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{financialaccount.Label}
	default:
		return nil, &NotSingularError{financialaccount.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (faq *FinancialAccountQuery) OnlyX(ctx context.Context) *FinancialAccount {
	node, err := faq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only FinancialAccount ID in the query.
// Returns a *NotSingularError when more than one FinancialAccount ID is found.
// Returns a *NotFoundError when no entities are found.
func (faq *FinancialAccountQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = faq.Limit(2).IDs(newQueryContext(ctx, TypeFinancialAccount, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{financialaccount.Label}
	default:
		err = &NotSingularError{financialaccount.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (faq *FinancialAccountQuery) OnlyIDX(ctx context.Context) string {
	id, err := faq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of FinancialAccounts.
func (faq *FinancialAccountQuery) All(ctx context.Context) ([]*FinancialAccount, error) {
	ctx = newQueryContext(ctx, TypeFinancialAccount, "All")
	if err := faq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*FinancialAccount, *FinancialAccountQuery]()
	return withInterceptors[[]*FinancialAccount](ctx, faq, qr, faq.inters)
}

// AllX is like All, but panics if an error occurs.
func (faq *FinancialAccountQuery) AllX(ctx context.Context) []*FinancialAccount {
	nodes, err := faq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of FinancialAccount IDs.
func (faq *FinancialAccountQuery) IDs(ctx context.Context) ([]string, error) {
	var ids []string
	ctx = newQueryContext(ctx, TypeFinancialAccount, "IDs")
	if err := faq.Select(financialaccount.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (faq *FinancialAccountQuery) IDsX(ctx context.Context) []string {
	ids, err := faq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (faq *FinancialAccountQuery) Count(ctx context.Context) (int, error) {
	ctx = newQueryContext(ctx, TypeFinancialAccount, "Count")
	if err := faq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, faq, querierCount[*FinancialAccountQuery](), faq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (faq *FinancialAccountQuery) CountX(ctx context.Context) int {
	count, err := faq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (faq *FinancialAccountQuery) Exist(ctx context.Context) (bool, error) {
	ctx = newQueryContext(ctx, TypeFinancialAccount, "Exist")
	switch _, err := faq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (faq *FinancialAccountQuery) ExistX(ctx context.Context) bool {
	exist, err := faq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the FinancialAccountQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (faq *FinancialAccountQuery) Clone() *FinancialAccountQuery {
	if faq == nil {
		return nil
	}
	return &FinancialAccountQuery{
		config:     faq.config,
		limit:      faq.limit,
		offset:     faq.offset,
		order:      append([]OrderFunc{}, faq.order...),
		inters:     append([]Interceptor{}, faq.inters...),
		predicates: append([]predicate.FinancialAccount{}, faq.predicates...),
		withOwner:  faq.withOwner.Clone(),
		// clone intermediate query.
		sql:    faq.sql.Clone(),
		path:   faq.path,
		unique: faq.unique,
	}
}

// WithOwner tells the query-builder to eager-load the nodes that are connected to
// the "owner" edge. The optional arguments are used to configure the query builder of the edge.
func (faq *FinancialAccountQuery) WithOwner(opts ...func(*UserQuery)) *FinancialAccountQuery {
	query := (&UserClient{config: faq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	faq.withOwner = query
	return faq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		IsActive bool `json:"is_active,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.FinancialAccount.Query().
//		GroupBy(financialaccount.FieldIsActive).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (faq *FinancialAccountQuery) GroupBy(field string, fields ...string) *FinancialAccountGroupBy {
	faq.fields = append([]string{field}, fields...)
	grbuild := &FinancialAccountGroupBy{build: faq}
	grbuild.flds = &faq.fields
	grbuild.label = financialaccount.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		IsActive bool `json:"is_active,omitempty"`
//	}
//
//	client.FinancialAccount.Query().
//		Select(financialaccount.FieldIsActive).
//		Scan(ctx, &v)
func (faq *FinancialAccountQuery) Select(fields ...string) *FinancialAccountSelect {
	faq.fields = append(faq.fields, fields...)
	sbuild := &FinancialAccountSelect{FinancialAccountQuery: faq}
	sbuild.label = financialaccount.Label
	sbuild.flds, sbuild.scan = &faq.fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a FinancialAccountSelect configured with the given aggregations.
func (faq *FinancialAccountQuery) Aggregate(fns ...AggregateFunc) *FinancialAccountSelect {
	return faq.Select().Aggregate(fns...)
}

func (faq *FinancialAccountQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range faq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, faq); err != nil {
				return err
			}
		}
	}
	for _, f := range faq.fields {
		if !financialaccount.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if faq.path != nil {
		prev, err := faq.path(ctx)
		if err != nil {
			return err
		}
		faq.sql = prev
	}
	return nil
}

func (faq *FinancialAccountQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*FinancialAccount, error) {
	var (
		nodes       = []*FinancialAccount{}
		withFKs     = faq.withFKs
		_spec       = faq.querySpec()
		loadedTypes = [1]bool{
			faq.withOwner != nil,
		}
	)
	if faq.withOwner != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, financialaccount.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*FinancialAccount).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &FinancialAccount{config: faq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, faq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := faq.withOwner; query != nil {
		if err := faq.loadOwner(ctx, query, nodes, nil,
			func(n *FinancialAccount, e *User) { n.Edges.Owner = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (faq *FinancialAccountQuery) loadOwner(ctx context.Context, query *UserQuery, nodes []*FinancialAccount, init func(*FinancialAccount), assign func(*FinancialAccount, *User)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*FinancialAccount)
	for i := range nodes {
		if nodes[i].user_financial_accounts == nil {
			continue
		}
		fk := *nodes[i].user_financial_accounts
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_financial_accounts" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (faq *FinancialAccountQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := faq.querySpec()
	_spec.Node.Columns = faq.fields
	if len(faq.fields) > 0 {
		_spec.Unique = faq.unique != nil && *faq.unique
	}
	return sqlgraph.CountNodes(ctx, faq.driver, _spec)
}

func (faq *FinancialAccountQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   financialaccount.Table,
			Columns: financialaccount.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: financialaccount.FieldID,
			},
		},
		From:   faq.sql,
		Unique: true,
	}
	if unique := faq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := faq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, financialaccount.FieldID)
		for i := range fields {
			if fields[i] != financialaccount.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := faq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := faq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := faq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := faq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (faq *FinancialAccountQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(faq.driver.Dialect())
	t1 := builder.Table(financialaccount.Table)
	columns := faq.fields
	if len(columns) == 0 {
		columns = financialaccount.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if faq.sql != nil {
		selector = faq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if faq.unique != nil && *faq.unique {
		selector.Distinct()
	}
	for _, p := range faq.predicates {
		p(selector)
	}
	for _, p := range faq.order {
		p(selector)
	}
	if offset := faq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := faq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// FinancialAccountGroupBy is the group-by builder for FinancialAccount entities.
type FinancialAccountGroupBy struct {
	selector
	build *FinancialAccountQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (fagb *FinancialAccountGroupBy) Aggregate(fns ...AggregateFunc) *FinancialAccountGroupBy {
	fagb.fns = append(fagb.fns, fns...)
	return fagb
}

// Scan applies the selector query and scans the result into the given value.
func (fagb *FinancialAccountGroupBy) Scan(ctx context.Context, v any) error {
	ctx = newQueryContext(ctx, TypeFinancialAccount, "GroupBy")
	if err := fagb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FinancialAccountQuery, *FinancialAccountGroupBy](ctx, fagb.build, fagb, fagb.build.inters, v)
}

func (fagb *FinancialAccountGroupBy) sqlScan(ctx context.Context, root *FinancialAccountQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(fagb.fns))
	for _, fn := range fagb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*fagb.flds)+len(fagb.fns))
		for _, f := range *fagb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*fagb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := fagb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// FinancialAccountSelect is the builder for selecting fields of FinancialAccount entities.
type FinancialAccountSelect struct {
	*FinancialAccountQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (fas *FinancialAccountSelect) Aggregate(fns ...AggregateFunc) *FinancialAccountSelect {
	fas.fns = append(fas.fns, fns...)
	return fas
}

// Scan applies the selector query and scans the result into the given value.
func (fas *FinancialAccountSelect) Scan(ctx context.Context, v any) error {
	ctx = newQueryContext(ctx, TypeFinancialAccount, "Select")
	if err := fas.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FinancialAccountQuery, *FinancialAccountSelect](ctx, fas.FinancialAccountQuery, fas, fas.inters, v)
}

func (fas *FinancialAccountSelect) sqlScan(ctx context.Context, root *FinancialAccountQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(fas.fns))
	for _, fn := range fas.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*fas.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := fas.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
