name: Continuous Integration

on:
  push:
    branches: [ master, 'feature/**', 'hotfix/**', 'fix/**' ]
    paths:
      - '**.go'
      - '**.mod'
      - '.github/workflows/**.yml'
      - '.golangci.yml'
  pull_request:
    branches: [ master ]
    paths:
      - '**.go'
      - '**.mod'
      - '.golangci.yml'

permissions:
  contents: read
  pull-requests: read

jobs:
  lint-test-build:
    uses: ./.github/workflows/lint-test-build.yml
#     secrets:
#       GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
