name: Continuous Integration

on:
  workflow_call:
    secrets:
      GH_ACCESS_TOKEN:
        required: false

env:
# Add line if using private modules
#   GOPRIVATE: 'github.com/maestre3d/*'
#   GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
  GO111MODULE: 'on'

permissions:
  contents: read
  pull-requests: read

jobs:
  lint:
    name: Run Go Linter
    strategy:
      matrix:
        go-version: [ 1.18 ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
          
# ADD line if using private modules
#       - name: Configure private modules
#         run: git config --global url.https://$GH_ACCESS_TOKEN@github.com/.insteadOf https://github.com/

      - name: Run linter
        uses: golangci/golangci-lint-action@v3.2.0
        with:
          version: latest

  unit-testing:
    name: Run Unit Tests
    strategy:
      matrix:
        go-version: [ 1.18, 1.19 ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

#       - name: Configure private modules
#         run: git config --global url.https://$GH_ACCESS_TOKEN@github.com/.insteadOf https://github.com/

      - name: Run Unit Testing
        run: go test ./... -cover -v

  integration-testing:
    name: Run Integration Tests
    strategy:
      matrix:
        go-version: [ 1.18, 1.19 ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    needs: ['unit-testing']
    steps:
      - uses: actions/checkout@v3
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

#       - name: Configure private modules
#         run: git config --global url.https://$GH_ACCESS_TOKEN@github.com/.insteadOf https://github.com/

      - name: Start Infrastructure
        run: docker-compose up -d

      - name: Run Integration Testing
        run: go test ./... -tags=integration

  build:
    name: Build artifact
    strategy:
      matrix:
        go-version: [ 1.18, 1.19 ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

#       - name: Configure private modules
#         run: git config --global url.https://$GH_ACCESS_TOKEN@github.com/.insteadOf https://github.com/

      - name: Build artifact
        run: go build cmd/http-api/main.go
