// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Card is the predicate function for card builders.
type Card func(*sql.Selector)

// Contact is the predicate function for contact builders.
type Contact func(*sql.Selector)

// FinancialAccount is the predicate function for financialaccount builders.
type FinancialAccount func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
