// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Contact is the predicate function for contact builders.
type Contact func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
